language: ruby
rvm:
  - 2.5.3
before_install: 
   - gem install bundler
script: 
  - bundle install --job=3 --retry=3
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec